test_mysql2: &test_mysql2
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

test_pg: &test_pg
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
  encoding: utf8

development:
  database: acts-as-constrained-dev
  <<: *test_<%= ActsAsConstrained.installed_db_gem %>

test:
  database: acts_as_constrained_test
  <<: *test_<%= ActsAsConstrained.installed_db_gem %>
